Colegio de Valuadores de Tamaulipas/Controllers/CMS/PortadaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using ColegioValuadoresTamaulipas.Models;

namespace ColegioValuadoresTamaulipas.Controllers.CMS
{
    [Authorize]
    public class PortadaController : Controller
    {

        CMSDbContext db = new CMSDbContext();

        // GET: Portada
        public ActionResult Index()
        {
            return View( db.Inicio.First() );
        }

        [HttpPost]
        public ActionResult Guardar( Inicio inicio )
        {
            if( ModelState.IsValid )
            {
                db.Entry(inicio).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index", "Sitio");
            }

            ModelState.AddModelError("", "Ocurrió un error al guardar los valores.");
            return View();

        }
    }
}

Colegio de Valuadores de Tamaulipas/Views/Portada/Index.cshtml
@model ColegioValuadoresTamaulipas.Models.Inicio

@{
    Layout = "";
}

<h2>Portada de sitio</h2>

@using (Html.BeginForm("Guardar", "Portada"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Portada</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mensaje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Mensaje, new { id = "editorPortada" })
                @Html.ValidationMessageFor(model => model.Mensaje, "", new { @class = "text-danger" })
                <script type="text/javascript">
                    CKEDITOR.replace("editorPortada");
                </script>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}